apiVersion: v1
kind: LimitRange
metadata:
  name: ...-limit-range
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "100"
    persistentvolumeclaims: "100"
    services.loadbalancers: "200"
    services.nodeports: "0"
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 256Mi
        cpu: "0.25"
      max:
        memory: 1Gi
      min:
        memory: 500Mi
      type: Container
