name: data-mesh

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "slides-data-mesh.md"
      # - "slides/data-mesh/*.md"
      - "package.json"
      - ".github/workflows/data-mesh.yml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: install dependencies
        run: npm install
      - name: slides-build
        run: npm run build:data-mesh
      - name: slides-ls
        run: ls -l data-mesh
