name: slidev-pages
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      # - "slides-*.md"
      # - "slides/**/*.md"
      - "package.json"
      - ".github/workflows/deploy.yml"
      - "public/index.html"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: install dependencies
        run: npm install
      - name: slides-build
        run: npm run build
      - name: slides-copy
        run: |
          chmod 755 *.sh
          ./copy-slides.sh
      - run: ls -l public
      - run: git config --global user.email "rock.c.c.hu@gmail.com"
      - run: git config --global user.name "Rock Hu"
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: npm install
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: rock-hu/slidev
          BRANCH: gh-pages
          FOLDER: public
