name: slidev-pages
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "slides-*.md"
      - "slides/**/*.md"
      - "package.json"
      - ".github/workflows/deploy.yml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: install dependencies
        run: npm install
      - name: slides-build
        run: npm run build
      - name: slides-copy
        run: |
          chmod 755 *.sh
          ./copy-slides.sh
      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
          name: github-pages
          retention-days: 1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
