name: wiremock

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "slides-wiremock.md"
      - "slides/wiremock/*.md"
      - "package.json"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: install dependencies
        run: npm install
      - name: slides-build
        run: npm run build:wiremock
      - name: slides-ls
        run: ls -l wiremock
